# Generated by Django 3.0.1 on 2019-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, null=True, verbose_name='Rua')),
                ('number', models.IntegerField(null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(max_length=100, null=True, verbose_name='Bairro')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='Cidade')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='País')),
            ],
        ),
    ]
