# Generated by Django 3.0.1 on 2019-12-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nome')),
                ('age', models.CharField(max_length=20, null=True, verbose_name='idade')),
                ('pis', models.CharField(max_length=30, verbose_name='PIS')),
                ('year_contribution', models.IntegerField(verbose_name='Anos_de_Contribuicao')),
                ('function', models.CharField(max_length=150, verbose_name='Cargo_na_Empresa')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.Address', verbose_name='Endereço_Pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
