# Generated by Django 3.0.1 on 2019-12-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, verbose_name='Nome')),
                ('description', models.CharField(max_length=1000, null=True, verbose_name='Descricao_Produto')),
            ],
        ),
    ]
